name: hack

on:
  push:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:

  generate-jobs:
    name: Generate Jobs
    runs-on: ubuntu-latest
    outputs:
      strategy: ${{ steps.strategy.outputs.strategy }}
    steps:
      - uses: actions/checkout@v4
      - id: strategy
        run: |
          strategy="$(jq -nc -f .github/workflows/ci.jq)"
          printf 'strategy=%s\n' "$strategy" >> "$GITHUB_OUTPUT"

  test:
    needs: generate-jobs
    strategy: ${{ fromJson(needs.generate-jobs.outputs.strategy) }}
    name: foo
    runs-on: ubuntu-latest
    steps: ${{ matrix.steps }}
