name: docker version

on:
  pull_request:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  docker-version:
    strategy:
      matrix:
        runner:
          # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
          - windows-2022
          - windows-2025
          #- ubuntu-22.04
          #- ubuntu-22.04-arm
          #- ubuntu-24.04
          #- ubuntu-24.04-arm
        try: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - run: 'docker version'
      - name: logs
        if: always()
        #shell: powershell
        # TODO Linux
        run: |
          powershell -Command 'Get-EventLog -LogName System -EntryType Error,Warning | Export-Csv -Path system_logs.csv'
          powershell -Command 'Get-EventLog -LogName Application -EntryType Error,Warning | Export-Csv -Path application_logs.csv'
          cat system_logs.csv
          cat application_logs.csv
      - name: upload logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: windows-system-logs-${{ matrix.runner }}-${{ matrix.try }}
          path: |
            system_logs.csv
            application_logs.csv
