name: test

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: 'bash --noprofile --norc -Eeuo pipefail -x {0}'

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-22.04
          - ubuntu-20.04
        generator:
          - docker/buildkit-syft-scanner
          - docker/scout-sbom-indexer
    runs-on: ${{ matrix.os }}
    steps:
      - name: test
        env:
          generator: ${{ matrix.generator }}
        run: |
          docker buildx create --name test
          docker buildx build --builder test --attest type=sbom,generator="$generator" --output type=oci,dest=oci,tar=false - <<<'FROM alpine'
          sbomFiles="$(jq '.manifests[].digest | "oci/blobs/" + sub(":"; "/")' oci/index.json | xargs -rt jq '.manifests[].digest | "oci/blobs/" + sub(":"; "/")' | xargs -rt jq '.layers[] | select(.annotations["in-toto.io/predicate-type"] == "https://spdx.dev/Document") | .digest | "oci/blobs/" + sub(":"; "/")')"
          xargs <<<"$sbomFiles" -rt jq -r '.predicate.packages | length'
          xargs <<<"$sbomFiles" -rt jq -r '.predicate.packages[] | .name, (.externalRefs | tojson)'

      - uses: actions/upload-artifact@v4
        with:
          name: oci-${{ matrix.os }}-${{ matrix.generator }}
          path: oci
